name: dart_uids
description: Service for generating unique identifiers (uids) 
version: 0.0.1
authors: 
  - Stepanov Mihail
  - Korolovskiy Evgeniy
  - Sheronov Timofei

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  yaml: "^2.1.13"

dev_dependencies:
  test: ^0.12.0